---
apiVersion: v1
name: kubebench-sa-adapter-private
description: To deploy kubebench-sa-adapter-private
version: 0.0.1
appVersion: 0.0.1
icon: https://avatars.github.ibm.com/u/56137?s=400
maintainers:
- name: Sunil Singh
  email: sksingh11@in.ibm.com
